apply plugin: "java-library"

base {
    archivesName = "${rootProject.archives_base_name}-core"
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
}

test {
    useJUnitPlatform()
}

tasks.register("benchmarkRopeRuntime", JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass.set("io.github.bladeswillfall.spelunkingrope.core.runtime.DenseRopeRuntimeBenchmark")
}
